OnlineExamSytem/OnlineExamSytem/Controllers/ExamController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using OnlineExamSytem.DAL;
using OnlineExamSytem.Models;
using Microsoft.AspNet.Identity;

namespace OnlineExamSytem.Controllers
{
    public class ExamController : BaseController
    {
        private ESOContext db = new ESOContext();
        private ApplicationDbContext IdentityDb = new ApplicationDbContext();
        private List<int> list;
        private static int currrentQuestion = 0;
       
        public ExamController()
        {
            this.list = new List<int>();

        }

        public ActionResult DoQuiz()
        {
            List<string> categoryNames = new List<string>();
            foreach (Category c in db.Categories.ToList())
                categoryNames.Add(c.name);

            List<int> levels = new List<int>();
            levels.Add(1); levels.Add(2); levels.Add(3);

            List<string> lang = new List<string>();
            lang.Add("Tr"); lang.Add("Fr"); lang.Add("En");

            List<int> questNumber = new List<int>();
            questNumber.Add(1);

            ViewBag.categoryNames = new SelectList(categoryNames);
            ViewBag.quizLevels = new SelectList(levels);
            ViewBag.langNames = new SelectList(lang);
            ViewBag.quizQuestNumber = new SelectList(questNumber);
            return View();
        }

        private List<Question> generate(string categoryNames, string quizLevels, string langNames, int numOfQuestion)
        {
            Random rand = new Random();
            List<int> result = new List<int>();
            HashSet<int> check = new HashSet<int>();
            List<Question> listQuestion = GetQuestCount(categoryNames, quizLevels, langNames);
            for (int i = 0; i < numOfQuestion; i++)
            {
                int curValue = rand.Next(1, listQuestion.Count());
                while (check.Contains(curValue))
                {
                    curValue = rand.Next(1, listQuestion.Count());
                }
                result.Add(curValue);
                check.Add(curValue);
            }

            List<Question> generatedList = new List<Question>();
            for (int i = 0; i < result.Count(); i++)
            {
                generatedList.Add(listQuestion[result[i]]);
            }
            return generatedList;
        }

        [HttpGet]
        public ActionResult StartQuiz(string categoryNames, string quizLevels, string langNames, string quizQuestNumber)
        {
            currrentQuestion = 0;
           
            List<Question> listQuestion = generate(categoryNames, quizLevels, langNames, Int32.Parse(quizQuestNumber));
            Session["list"] = listQuestion;
            Question quest = listQuestion[currrentQuestion];
            return Json(quest, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult SendData(string categoryNames, string quizLevels, string langNames, string quizQuestNumber)
        {
            currrentQuestion = 0;
            List<Question> listQuestion = generate(categoryNames, quizLevels, langNames, Int32.Parse(quizQuestNumber));
            Session["list"] = listQuestion;
            Question quest = listQuestion[currrentQuestion];
            return Json(listQuestion, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public String Terminate(string score, string questNumber, string trueQuestionNumber, string falseQuestionNumber)
        {
            Exam exam = new Exam();
            string userId = User.Identity.GetUserId();
            ApplicationUser user = IdentityDb.Users.Find(userId);
            exam.Identifier = user.UserName.Substring(0, 2) + user.DogumGunu.ToString().Substring(0, 2);
            exam.Date = DateTime.Now;
            exam.Score = Int32.Parse(score);
            exam.Owner = user.UserName;
            exam.QuestionNumber = Int32.Parse(questNumber);
            exam.TrueQuestionNumber = Int32.Parse(trueQuestionNumber);
            exam.FalseQuestionNumber = Int32.Parse(falseQuestionNumber);
            exam.ExamTime = GetExamTime();
            List<Question> list = (List<Question>)Session["list"];
            for (int i = 0; i < list.Count(); i++)
            {
               db.Questions.Remove(db.Questions.Find(list[i].ID));
           }
            db.SaveChanges();
            exam.ListQuestion = list;
            user.userExams.Add(exam);
          //  user.userExams = user.userExams;
            IdentityDb.Entry(user).State = EntityState.Modified;
            db.Entry(exam).State = EntityState.Modified;
            IdentityDb.SaveChanges();
            Session["exam"] = exam;

            return "Exam/ShowExamDetails";

        }

        [HttpGet]
        public ActionResult ShowExamDetails(int? id)
        {
            Exam exam;
            if(id==null)
                exam =(Exam)Session["exam"];
            else
            {
                exam = db.Exams.Find(id);
            }

            return View(exam);
        }

        [HttpGet]
        public ActionResult NextQuestion(string categoryNames, string quizLevels, string langNames, string quizQuestNumber)
        {
            List<Question> list = generate(categoryNames, quizLevels, langNames, Int32.Parse(quizQuestNumber));
            if (currrentQuestion < list.Count() - 1)
                currrentQuestion++;
           Question quest = list[currrentQuestion];
           
            return Json(quest, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public int GetExamTime()
        {
            List<Question> list = (List<Question>)Session["list"];
            int time=0;
            for(int i=0; i<list.Count(); i++)
                time+= list[i].time;
            return time;

        }

        

        private List<Question> GetQuestCount(string categoryNames, string quizLevels, string langNames)
        {
           
            List<Question> listQuestion = new List<Question>();
            foreach (Question q in db.Questions.ToList())
            {
                if (q.category.Equals(categoryNames, StringComparison.CurrentCultureIgnoreCase) &&
                    q.level == Int32.Parse(quizLevels) && q.language.Equals(langNames, StringComparison.CurrentCultureIgnoreCase) 
                    && q.status.Equals("aktif", StringComparison.CurrentCultureIgnoreCase))
                {
                    listQuestion.Add(q);
                }
            }
            return listQuestion;
        }

        [HttpGet]
        public ActionResult GetJsonData(string categoryNames, string quizLevels, string langNames)
        {
            List<Question> list = GetQuestCount(categoryNames, quizLevels, langNames);
            List<int> listOfIndices = new List<int>();
            for (int i = 1; i <= list.Count(); i++)
               listOfIndices.Add(i);

            return Json(listOfIndices, JsonRequestBehavior.AllowGet);

        }
        // GET: Exam
        public ActionResult Index()
        {
            string userId = User.Identity.GetUserId();
            ApplicationUser user = IdentityDb.Users.Find(userId);
            if (user.rol.Equals("user", StringComparison.CurrentCultureIgnoreCase))
                return View(user.userExams.ToList());
            else
                return View(db.Exams.ToList());
        }

        // GET: Exam/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Exam exam = db.Exams.Find(id);
            if (exam == null)
            {
                return HttpNotFound();
            }
            return View(exam);
        }

        // GET: Exam/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Exam/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ExamID,Identifier,Date,Score,Owner,QuestionNumber,TrueQuestionNumber,FalseQuestionNumber,ID")] Exam exam)
        {
            if (ModelState.IsValid)
            {
                db.Exams.Add(exam);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(exam);
        }

        // GET: Exam/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Exam exam = db.Exams.Find(id);
            if (exam == null)
            {
                return HttpNotFound();
            }
            return View(exam);
        }

        // POST: Exam/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ExamID,Identifier,Date,Score,Owner,QuestionNumber,TrueQuestionNumber,FalseQuestionNumber,ID")] Exam exam)
        {
            if (ModelState.IsValid)
            {
                db.Entry(exam).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(exam);
        }

        // GET: Exam/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Exam exam = db.Exams.Find(id);

OnlineExamSytem/OnlineExamSytem/Controllers/LanguageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OnlineExamSytem.Helpers;

namespace OnlineExamSytem.Controllers
{
    public class LanguageController : BaseController
    {
        public ActionResult SetCulture(string culture, string returnUrl)
        {
            // Validate input
            culture = CultureHelper.GetImplementedCulture(culture);
            RouteData.Values["culture"] = culture;
            if (returnUrl != "/")
            {
                if (returnUrl.Contains("tr"))  // set culture
                    returnUrl = returnUrl.Replace("tr", culture);
                else if (returnUrl.Contains("fr"))  // set culture
                    returnUrl = returnUrl.Replace("fr", culture);
                else
                    returnUrl = returnUrl.Replace("en-us", culture);
            }
            else
            {
                returnUrl = returnUrl + culture;
            }

            Console.WriteLine(returnUrl);

            return Redirect(returnUrl);
        }

    }
}

OnlineExamSytem/OnlineExamSytem/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using OnlineExamSytem.Models;

namespace OnlineExamSytem.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UsersController : BaseController
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Users
        public ActionResult GetAllUsers()
        {
            return View("GetAllUsers", db.Users.ToList());
        }

        // GET: Users/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ApplicationUser applicationUser = db.Users.Find(id);
            if (applicationUser == null)
            {
                return HttpNotFound();
            }
            return View(applicationUser);
        }

        // GET: Users/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Users/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ApplicationUser applicationUser)
        {
            if (ModelState.IsValid)
            {
                db.Users.Add(applicationUser);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(applicationUser);
        }

        // GET: Users/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ApplicationUser applicationUser = db.Users.Find(id);
            if (applicationUser == null)
            {
                return HttpNotFound();
            }
            return View(applicationUser);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ApplicationUser applicationUser)
        {
            if (ModelState.IsValid)
            {
                db.Entry(applicationUser).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(applicationUser);
        }

        // GET: Users/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ApplicationUser applicationUser = db.Users.Find(id);
            if (applicationUser == null)
            {
                return HttpNotFound();
            }
            return View(applicationUser);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            ApplicationUser applicationUser = db.Users.Find(id);
            db.Users.Remove(applicationUser);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

OnlineExamSytem/OnlineExamSytem/Views/Shared/_CategoryPartial.cshtml
<div class="categoryPartialLinks_div">
    <div class="container-fluid" style="margin-top:20px;">
        <div class="row">
            <div class="col-sm-3">
                <a href="@Url.Action("GetAllCategories", "Category")">
                    <span class="glyphicon glyphicon-list-alt" aria-hidden="true" style="font-size:20px; color:#EF9A9A; margin-top:8px;"></span>
                    <label class="category_par"> Category List </label>
                </a>
            </div>
            <div class="col-sm-3">
                <a href="@Url.Action("Create", "Category")" class="user_par">
                    <span class="glyphicon glyphicon-plus" aria-hidden="true" style="font-size:20px; color:#EF9A9A; margin-top:7px;"></span>
                    <label class="category_par"> Add Category </label>
                </a>
            </div>
        </div>
    </div>
</div>

OnlineExamSytem/OnlineExamSytem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Online Examm System", "Dashboard", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink(Resource.layout_dsh, "Dashboard", "Home")</li>
                    <li>@Html.ActionLink(Resource.layout_about, "About", "Home")</li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <span>
                              @Resource.layout_language   <i class="fa fa-caret-down"></i>
                            </span>
                        </a>
                        <ul class="dropdown-menu">
                            <li> @Html.ActionLink(Resource.layout_language_choice_tr, "SetCulture", "Language", new { culture = "tr", returnUrl = this.Request.RawUrl }, null) </li>
                            <li class="divider"></li>
                            <li> @Html.ActionLink(Resource.layout_language_choice_fr, "SetCulture", "Language", new { culture = "fr", returnUrl = this.Request.RawUrl }, null) </li>
                            <li class="divider"></li>
                            <li> @Html.ActionLink(Resource.layout_language_choice_en, "SetCulture", "Language", new { culture = "en", returnUrl = this.Request.RawUrl }, null) </li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <span>
                                @User.Identity.Name   <i class="fa fa-caret-down"></i> </span> 
                            <img src="~/Assets/img.jpg" alt="Dangerfield" style=" width:20px; height:25px; border-radius:50%;" />
                        </a>
                        <ul class="dropdown-menu">
                            <li> <img src="~/Assets/img.jpg" alt="Dangerfield" style=" width:160px; height:150px;"/></li>
                            <li class="divider"></li>
                            <li> 
                                 @Html.ActionLink(Resource.layout_session_settings, "Dashboard", "Home", null, new { @class = "fa fa-cog" }) 
                            </li>
                            <li class="divider"></li>
                            @using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm" }))
                            {
                                @Html.AntiForgeryToken()
                                
                                    <li><a class="fa fa-sign-out" href="javascript:document.getElementById('logoutForm').submit()">@Resource.layout_session_close</a></li>
                               
                            }
                            
                            <li class="divider"></li>
                            <li>
                                @Html.ActionLink(Resource.layout_profil, "Dashboard", "Home", null, new { @class = "fa fa-user-circle" })
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container-fluid">
        <div class="row">
                <div class="col-sm-3">
                    <div class="panel panel-default">
                        <!-- Default panel contents -->
                        <div class="panel-heading" style="text-align:center;">@Resource.lay_panel_left_title</div>
                        <div class="panel-body">
                            <img src="~/Assets/graduation_cup.jpg" alt="graduation_cup" style="display: block; margin-left: auto; margin-right: auto;"/>
                        </div>
                        <a href="@Url.Action("Dashboard", "Home")" class="list-group-item">
                            <span class="glyphicon glyphicon-home" aria-hidden="true" style="font-size:20px; color:#D81B60;"></span>
                            <label class="lay_left_menu_texts"> @Resource.layout_dsh </label>
                        </a>
@if (User.IsInRole("Admin"))
{
                        <a href="@Url.Action("GetAllCategories", "Category")" class="list-group-item">
                            <span class="glyphicon glyphicon-folder-open" aria-hidden="true" style="font-size:20px; color:#B71C1C;"></span>
                            <span class="badge">@ViewBag.catCount</span>
                            <label class="lay_left_menu_texts"> @Resource.layout_category </label>
                        </a>

                        <a href="@Url.Action("GetAllUsers", "Users")" class="list-group-item">
                            <span class="glyphicon glyphicon-user" aria-hidden="true" style="font-size:20px; color:#6E88A3;"></span>
                            <span class="badge">@ViewBag.userCount</span>
                            <label class="lay_left_menu_texts"> @Resource.layout_user </label>
                        </a>
}
                        <a href="@Url.Action("Index", "Exam")" class="list-group-item">
                            <span class="glyphicon glyphicon-book" aria-hidden="true" style="font-size:20px; color:#00796B;"></span>
                            <span class="badge">@ViewBag.examCount</span>
                            <label class="lay_left_menu_texts"> @Resource.layout_exam </label>
                        </a>
@if (User.IsInRole("Admin"))
{
                        <a href="@Url.Action("GetAllQuestions", "Question")" class="list-group-item">
                            <span class="glyphicon glyphicon-list-alt" aria-hidden="true" style="font-size:20px; color:#757575;"></span>
                            <span class="badge"> @ViewBag.questCount </span>
                            <label class="lay_left_menu_texts"> @Resource.layout_question </label>

                        </a>
}
                        <a href="@Url.Action("ChangePassword", "Manage")" class="list-group-item">
                            <i class="fa fa-cog" aria-hidden="true" style="font-size:20px; color:#1976D2;"></i>
                            <label class="lay_left_menu_texts"> @Resource.layout_settings </label>
                        </a>
                    </div>
                </div>

            <div class="col-sm-9">
                 @RenderBody()
           </div>
         </div>
    </div>
   
    <footer>
     
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

OnlineExamSytem/OnlineExamSytem/Views/Shared/_QuestionPartial.cshtml
<div class="questionPartialLinks_div">
    <div class="container-fluid" style="margin-top:20px;">
        <div class="row">
            <div class="col-sm-3">
                <a href="@Url.Action("GetAllQuestions", "Question")">
                    <span class="glyphicon glyphicon-list-alt" aria-hidden="true" style="font-size:20px; color:#80CBC4; margin-top:8px;"></span>
                    <label class="question_par"> Question List </label>
                </a>
            </div>
            <div class="col-sm-3">
                <a href="@Url.Action("Create", "Question")" class="user_par">
                    <span class="glyphicon glyphicon-plus" aria-hidden="true" style="font-size:20px; color:#80CBC4; margin-top:7px;"></span>
                    <label class="question_par"> Add Question </label>
                </a>
            </div>
        </div>
    </div>
</div>

OnlineExamSytem/OnlineExamSytem/Views/Shared/_UserPartial.cshtml
<div class="userPartialLinks_div">
    <div class="container-fluid" style="margin-top:20px;">
        <div class="row">
            <div class="col-sm-2">
                <a href="@Url.Action("GetAllUsers", "Users")">
                    <span class="glyphicon glyphicon-list-alt" aria-hidden="true" style="font-size:20px; color:#F48FB1; margin-top:8px;"></span>
                    <label class="user_par"> User List </label>
                </a>
            </div>
            <div class="col-sm-2">
                <a href="@Url.Action("Register", "Account")" class="user_par">
                    <span class="glyphicon glyphicon-plus" aria-hidden="true" style="font-size:20px; color:#F48FB1; margin-top:7px;"></span>
                    <label class="user_par"> Add User </label>
                </a>
            </div>
        </div>
    </div>
</div>